### PR TITLE
Fix npm latest tag if the new version is lower than previous

### LINKED ISSUE #2: support githubs flavor of semver
today `npm install electron-prebuilt -g` ended up installing a version of electron that was 674 commits old because they pushed out a release `v0.30.7` that overwrote the previously newest release `v0.33.1`

I think the version numbers they use for their releases have two major differences from semver:

- they don't increment the minor when adding new features (e.g. https://github.com/atom/electron/releases/tag/v0.31.2 should have been 0.32.0 because of the new APIs)
- they view each minor version (e.g. `0.31`, `0.32`) as a separate 'release channel', meaning if 0.33 is already out, they expect to be able to publish to 0.32 without affecting the latest version. this lets them do patch versions to fix tiny bugs in old electrons that atom is using so they can update quickly in atom without having to port atom to use the latest electron.

since these break the expectations of semver and npm, we need to do extra work here to make sure we publish electon versions in the right way:

- when doing a release, check the last release on npm. if the new version is higher than the old version, we can just do a publish as normal. however, is the new version is lower than the old version, we have to do prevent npm from publishing the `latest` tag, which is npms default

we fixed the issue today manually by running `npm tag electron-prebuilt@0.33.1 latest` which set the previous release as latest

cc @mafintosh @jlord

### PR DESCRIPTION
**Pull request by johnmuhl**
close #2

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -106,11 +107,32 @@ app.post('/', function (req, res) {
...
+          const info = response[0]
+          const lastVersion = info[Object.keys(info)[0]]['dist-tags'].latest
+          return publishAsync([release.tarball_url])
+          .catch(function (err) {
             console.error('Failed to publish package')
             throw err
-          }
+          })
+          .then(function () {
+            if (semver.gt(lastVersion, newVersion)) {
```
Comment (maxogden) [inline index.js]: +1 @johnmuhl, excellent work
